### ISSUE TITLE
Comaptibility issue with PHP 7.4

### ISSUE THREAD

**Issue by codemastering** [PayFast/mod-magento_2.3.0#4]
Hello

This module is not compatible with PHP 7.4 and Magento 2.4, I am getting below error while i am running php bin/magento setup:di:compile.

Deprecated Functionality: Cannot use "parent" when current class scope has no parent in /app/code/Payfast/Payfast/Model/Payfast.php on line 274

Please fix and release this module for Magento 2.4 version soon.

Thank you

**Comment by byroncoetzee67** [comment]
Good Morning. Thank you contacting PayFast.

We are aware of the compatibility issue with Magento 2.4 a we have logged a developer support ticket for this to be attended to.

Please can you send an email to support@payfast.co.za so that we can log a support ticket on your behalf to track and communicate with you once the compatibility change has been made.  Also please not the there has been an update to Magento and it is now compatible up until version 2.3.5.

https://github.com/PayFast/mod-magento_2.3.0.git

I will await your email.

Kind regards

Byron C
PayFast Tech Support

**Comment by codemastering** [comment]
Thank you, Byron. I submitted the ticket (Ticket ID: 730891).

Awaiting an update for Magento 2.4.0

Thank you

**Comment by codemastering** [comment]
Hello Byron

Please advise any update on the compatibility of Magento 2.4.0 with the PayFast plugin?

Please reply soon

Thank you

**Comment by PF-Thinus** [comment]
Good morning Muhammad,

Please note, we have not yet updated the Magento plugin. We are in the process of creating a new Magento plugin to be compatible with 2.4. 

I see your ticket is still active and the agent is currently awaiting feedback from the developers. To avoid disappointment with response times, I suggest using the support line as the preferred method of communication as the agents do not always monitor the GitHub repositories.

Once the plugin is ready, we will reach out to you with a link for the Magento 2.4 plugin.

Kind regards, 
Thinus

**Comment by codemastering** [comment]
Hello Thinus

Can you please provide and ETA for Magento 2.4 update for PayFast plugin? I am waiting since long time now.

Kindly advise asap.

Thank you

**Comment by PF-Thinus** [comment]
Good morning Muhammad,

Unfortunately, I cannot give you an ETA as there are different projects we are also busy with.
The plugin is being worked on, however, there might be delays due to reviews and other projects of higher priority needing more urgent attention.

Kind regards,
Thinus

**Comment by codemastering** [comment]
alright, looking forward to it. Thank you.

**Comment by codemastering** [comment]
Hello @PF-Thinus 

Any update on the Magento 2.4 update?

Thanks

**Comment by PF-Thinus** [comment]
Hi @codemastering, 

With Black Friday and Cyber Monday taking the highest priority, we had it on the back burner.
We expect the plugin to be ready by end of Jan 2021, however, as previously mentioned, there might be other projects taking higher priority and hotfixes that need attention.

Kind regards,
Thinus

**Comment by codemastering** [comment]
Thank you for the feedback, @PF-Thinus

**Comment by MCBarnard** [comment]
Hi @codemastering ,

We have released the new Magento 2.4 plugin. It can be found here: https://github.com/PayFast/mod-magento_2.4.0
Please let me know if you encounter any issues.

Kind regards,
Thinus

**Comment by codemastering** [comment]
Thank you @MCBarnard 

Please confirm if this plugin is compatible with Magento 2.4.1 as well?

Awaiting your feedback.

Thank you

**Comment by MCBarnard** [comment]
Hi @codemastering ,

it is compatible with 2.4.1

**Comment by codemastering** [comment]
alright, thank you for the update. will advise if encountered with any issue. Thanks.
