### ISSUE TITLE
Compatibility with Magento v2.3.7

### ISSUE THREAD

**Issue by BevK01** [PayFast/mod-magento_2.3.0#9]
Having a PHP compatibility issue with Magento 2.3.7.  Needs to run on PHP 7.3.29 - getting error on PHP 7.4

Module supports Magento 2 up to v2.3.5

Deprecated Functionality: Cannot use "parent" when current class scope has no parent in /home/crystalc/public_html/app/code/Payfast/Payfast/Model/Payfast.php on line 287

**Comment by lefu007** [comment]
Good Morning, Please install this https://github.com/PayFast/mod-magento-subscriptions for magento 2.4.0 up.

**Comment by BevK01** [comment]
We are still having issues and are now having to look for another payment gateway as we are losing sales – about 30% down on expected sales for the last week and a half.

 

This plugin also seems to be for Magento 2.4.0 or higher versions.

We have tried in UAT and getting below error -

Column definition "customer_id" and reference column definition "entity_id" are different in tables "payfast_payfast_recurring_payment" and "customer_entity"

 

 

 

 

 

Kind regards

Beverly

 



www.crystalclawz.co.za

+27 (0)44 850 1133
